// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADNGuBTKjIaNY4kmMQmlDVV6Sj4FCxGaY',
    appId: '1:148500074078:web:3df6879e17e73acc7beecf',
    messagingSenderId: '148500074078',
    projectId: 'prakflutterfirebase-4a624',
    authDomain: 'prakflutterfirebase-4a624.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-4a624.appspot.com',
    measurementId: 'G-VWV5C2DDKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3wlQHTgeAwRlDKE3BXgsIr33Hn8tq9AU',
    appId: '1:148500074078:android:a92a4fa896300d307beecf',
    messagingSenderId: '148500074078',
    projectId: 'prakflutterfirebase-4a624',
    storageBucket: 'prakflutterfirebase-4a624.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK0xW4IQ6ITwZmGo0TnKUZgTMo-2olQc0',
    appId: '1:148500074078:ios:13a6eca3ae4aa4ca7beecf',
    messagingSenderId: '148500074078',
    projectId: 'prakflutterfirebase-4a624',
    storageBucket: 'prakflutterfirebase-4a624.appspot.com',
    androidClientId: '148500074078-me8qh5o6bclajnk21n5nv0c4422o2t43.apps.googleusercontent.com',
    iosClientId: '148500074078-rfmcko4v6b0uepu493g6irbfbbqm4vjp.apps.googleusercontent.com',
    iosBundleId: 'com.example.fic12FlutterStarter',
  );

}